// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWpIQHNM2s61QpniAQQVFNMlhYxqDMcEw',
    appId: '1:260208023947:web:aa123b4234bc25f0e3778e',
    messagingSenderId: '260208023947',
    projectId: 'ghichu-adb19',
    authDomain: 'ghichu-adb19.firebaseapp.com',
    storageBucket: 'ghichu-adb19.appspot.com',
    measurementId: 'G-E7DNYY85WM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc_A_i_tBIo_PG2kZS1AIhEKB4i1-ZuHw',
    appId: '1:260208023947:android:4522945f2a8484e8e3778e',
    messagingSenderId: '260208023947',
    projectId: 'ghichu-adb19',
    storageBucket: 'ghichu-adb19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCwyH0cBywhLBv8D-JJNYUtcfY4z6rkoE',
    appId: '1:260208023947:ios:0d394a89de34985de3778e',
    messagingSenderId: '260208023947',
    projectId: 'ghichu-adb19',
    storageBucket: 'ghichu-adb19.appspot.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCwyH0cBywhLBv8D-JJNYUtcfY4z6rkoE',
    appId: '1:260208023947:ios:0d394a89de34985de3778e',
    messagingSenderId: '260208023947',
    projectId: 'ghichu-adb19',
    storageBucket: 'ghichu-adb19.appspot.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWpIQHNM2s61QpniAQQVFNMlhYxqDMcEw',
    appId: '1:260208023947:web:f8f22ecb2f93fdafe3778e',
    messagingSenderId: '260208023947',
    projectId: 'ghichu-adb19',
    authDomain: 'ghichu-adb19.firebaseapp.com',
    storageBucket: 'ghichu-adb19.appspot.com',
    measurementId: 'G-HXRLED3KKE',
  );
}
